# Generated by Django 4.0.2 on 2022-02-17 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_classe_dominio_especie_familia_tag_vida_subespecie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classe',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='home.Tag'),
        ),
        migrations.AlterField(
            model_name='dominio',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='home.Tag'),
        ),
        migrations.AlterField(
            model_name='especie',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='home.Tag'),
        ),
        migrations.AlterField(
            model_name='familia',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='home.Tag'),
        ),
        migrations.AlterField(
            model_name='filo',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='home.Tag'),
        ),
        migrations.AlterField(
            model_name='genero',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='home.Tag'),
        ),
        migrations.AlterField(
            model_name='ordem',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='home.Tag'),
        ),
        migrations.AlterField(
            model_name='reino',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='home.Tag'),
        ),
        migrations.AlterField(
            model_name='subespecie',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='home.Tag'),
        ),
        migrations.AlterField(
            model_name='vida',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='imagens/'),
        ),
        migrations.AlterField(
            model_name='vida',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='home.Tag'),
        ),
    ]
