# Generated by Django 4.0.2 on 2022-02-17 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_classe_tags_alter_dominio_tags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classe',
            name='antepassados',
            field=models.ManyToManyField(blank=True, to='home.Classe'),
        ),
        migrations.AlterField(
            model_name='classe',
            name='tags',
            field=models.ManyToManyField(blank=True, to='home.Tag'),
        ),
        migrations.AlterField(
            model_name='dominio',
            name='antepassados',
            field=models.ManyToManyField(blank=True, to='home.Dominio'),
        ),
        migrations.AlterField(
            model_name='dominio',
            name='tags',
            field=models.ManyToManyField(blank=True, to='home.Tag'),
        ),
        migrations.AlterField(
            model_name='especie',
            name='antepassados',
            field=models.ManyToManyField(blank=True, to='home.Especie'),
        ),
        migrations.AlterField(
            model_name='especie',
            name='tags',
            field=models.ManyToManyField(blank=True, to='home.Tag'),
        ),
        migrations.AlterField(
            model_name='familia',
            name='antepassados',
            field=models.ManyToManyField(blank=True, to='home.Familia'),
        ),
        migrations.AlterField(
            model_name='familia',
            name='tags',
            field=models.ManyToManyField(blank=True, to='home.Tag'),
        ),
        migrations.AlterField(
            model_name='filo',
            name='antepassados',
            field=models.ManyToManyField(blank=True, to='home.Filo'),
        ),
        migrations.AlterField(
            model_name='filo',
            name='tags',
            field=models.ManyToManyField(blank=True, to='home.Tag'),
        ),
        migrations.AlterField(
            model_name='genero',
            name='antepassados',
            field=models.ManyToManyField(blank=True, to='home.Genero'),
        ),
        migrations.AlterField(
            model_name='genero',
            name='tags',
            field=models.ManyToManyField(blank=True, to='home.Tag'),
        ),
        migrations.AlterField(
            model_name='ordem',
            name='antepassados',
            field=models.ManyToManyField(blank=True, to='home.Ordem'),
        ),
        migrations.AlterField(
            model_name='ordem',
            name='tags',
            field=models.ManyToManyField(blank=True, to='home.Tag'),
        ),
        migrations.AlterField(
            model_name='reino',
            name='antepassados',
            field=models.ManyToManyField(blank=True, to='home.Reino'),
        ),
        migrations.AlterField(
            model_name='reino',
            name='tags',
            field=models.ManyToManyField(blank=True, to='home.Tag'),
        ),
        migrations.AlterField(
            model_name='subespecie',
            name='antepassados',
            field=models.ManyToManyField(blank=True, to='home.SubEspecie'),
        ),
        migrations.AlterField(
            model_name='subespecie',
            name='tags',
            field=models.ManyToManyField(blank=True, to='home.Tag'),
        ),
        migrations.AlterField(
            model_name='vida',
            name='antepassados',
            field=models.ManyToManyField(blank=True, to='home.Vida'),
        ),
        migrations.AlterField(
            model_name='vida',
            name='tags',
            field=models.ManyToManyField(blank=True, to='home.Tag'),
        ),
    ]
