# Generated by Django 4.0.2 on 2022-02-17 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_classe_antepassados_alter_classe_tags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vida',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='imagens/'),
        ),
    ]
