# Generated by Django 4.0.4 on 2022-06-01 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom_start_app', '0003_alter_image_test_options_alter_image_test_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='Taxon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Taxons',
            },
        ),
        migrations.CreateModel(
            name='Vida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('origin', models.BigIntegerField()),
                ('extintion', models.BigIntegerField(blank=True, null=True)),
                ('data_criação', models.DateTimeField(auto_now_add=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='imagens/')),
                ('image_2', models.FileField(blank=True, null=True, upload_to='imagens/')),
                ('image_3', models.FileField(blank=True, null=True, upload_to='imagens/')),
                ('description', models.TextField(blank=True, null=True)),
                ('description_language_II', models.TextField(blank=True, null=True)),
                ('antepassados', models.ManyToManyField(blank=True, to='custom_start_app.vida')),
                ('tags', models.ManyToManyField(blank=True, to='custom_start_app.tag')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='custom_start_app.taxon')),
            ],
            options={
                'verbose_name_plural': 'Vidas',
            },
        ),
    ]
