# Generated by Django 4.0.4 on 2022-06-02 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_tag_taxon_vida'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tag_images/'),
        ),
        migrations.AddField(
            model_name='tag',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='tag_images/'),
        ),
        migrations.AddField(
            model_name='tag',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='tag_images/'),
        ),
        migrations.AlterField(
            model_name='vida',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='vida',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='vida',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
