# Generated by Django 4.0.4 on 2022-06-03 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_tag_image_tag_image_2_tag_image_3_alter_vida_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vida',
            name='common_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='vida',
            name='name',
            field=models.CharField(max_length=80),
        ),
    ]
