# Generated by Django 4.0.2 on 2022-02-17 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('nome_popular', models.CharField(blank=True, max_length=100, null=True)),
                ('origem', models.BigIntegerField()),
                ('extinção', models.BigIntegerField(blank=True, null=True)),
                ('descrição', models.TextField(blank=True, null=True)),
                ('description_language_II', models.TextField(blank=True, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='imagens/')),
                ('image_2', models.FileField(blank=True, null=True, upload_to='imagens/')),
                ('image_3', models.FileField(blank=True, null=True, upload_to='imagens/')),
                ('antepassados', models.ManyToManyField(blank=True, null=True, to='home.Classe')),
            ],
            options={
                'verbose_name_plural': 'Classes',
            },
        ),
        migrations.CreateModel(
            name='Dominio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('nome_popular', models.CharField(blank=True, max_length=100, null=True)),
                ('origem', models.BigIntegerField()),
                ('extinção', models.BigIntegerField(blank=True, null=True)),
                ('descrição', models.TextField(blank=True, null=True)),
                ('description_language_II', models.TextField(blank=True, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='imagens/')),
                ('image_2', models.FileField(blank=True, null=True, upload_to='imagens/')),
                ('image_3', models.FileField(blank=True, null=True, upload_to='imagens/')),
                ('antepassados', models.ManyToManyField(blank=True, null=True, to='home.Dominio')),
            ],
            options={
                'verbose_name_plural': 'Dominios',
            },
        ),
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epíteto_específico', models.CharField(max_length=100)),
                ('nome_popular', models.CharField(blank=True, max_length=100, null=True)),
                ('origem', models.BigIntegerField()),
                ('extinção', models.BigIntegerField(blank=True, null=True)),
                ('descrição', models.TextField(blank=True, null=True)),
                ('description_language_II', models.TextField(blank=True, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='imagens/')),
                ('image_2', models.FileField(blank=True, null=True, upload_to='imagens/')),
                ('image_3', models.FileField(blank=True, null=True, upload_to='imagens/')),
                ('antepassados', models.ManyToManyField(blank=True, null=True, to='home.Especie')),
            ],
            options={
                'verbose_name_plural': 'Especies',
            },
        ),
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('nome_popular', models.CharField(blank=True, max_length=100, null=True)),
                ('origem', models.BigIntegerField()),
                ('extinção', models.BigIntegerField(blank=True, null=True)),
                ('descrição', models.TextField(blank=True, null=True)),
                ('description_language_II', models.TextField(blank=True, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='imagens/')),
                ('image_2', models.FileField(blank=True, null=True, upload_to='imagens/')),
                ('image_3', models.FileField(blank=True, null=True, upload_to='imagens/')),
                ('antepassados', models.ManyToManyField(blank=True, null=True, to='home.Familia')),
            ],
            options={
                'verbose_name_plural': 'Familias',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('data_criação', models.DateTimeField(auto_now_add=True)),
                ('descrição', models.TextField(blank=True, null=True)),
                ('description_language_II', models.TextField(blank=True, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='imagens/')),
                ('image2', models.FileField(blank=True, null=True, upload_to='imagens/')),
            ],
            options={
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='Vida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('origem', models.BigIntegerField()),
                ('extinção', models.BigIntegerField(blank=True, null=True)),
                ('data_criação', models.DateTimeField(auto_now_add=True)),
                ('descrição', models.TextField(blank=True, null=True)),
                ('description_language_II', models.TextField(blank=True, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='imagens/')),
                ('image_2', models.FileField(blank=True, null=True, upload_to='imagens/')),
                ('image_3', models.FileField(blank=True, null=True, upload_to='imagens/')),
                ('antepassados', models.ManyToManyField(blank=True, null=True, to='home.Vida')),
                ('tags', models.ManyToManyField(to='home.Tag')),
            ],
            options={
                'verbose_name_plural': 'Vidas',
            },
        ),
        migrations.CreateModel(
            name='SubEspecie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epíteto_subespecífico', models.CharField(max_length=100)),
                ('nome_popular', models.CharField(blank=True, max_length=100, null=True)),
                ('origem', models.BigIntegerField()),
                ('extinção', models.BigIntegerField(blank=True, null=True)),
                ('descrição', models.TextField(blank=True, null=True)),
                ('description_language_II', models.TextField(blank=True, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='imagens/')),
                ('image_2', models.FileField(blank=True, null=True, upload_to='imagens/')),
                ('image_3', models.FileField(blank=True, null=True, upload_to='imagens/')),
                ('antepassados', models.ManyToManyField(blank=True, null=True, to='home.SubEspecie')),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.especie')),
                ('tags', models.ManyToManyField(to='home.Tag')),
            ],
            options={
                'verbose_name_plural': 'Sub-Especies',
            },
        ),
        migrations.CreateModel(
            name='Reino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('nome_popular', models.CharField(blank=True, max_length=100, null=True)),
                ('origem', models.BigIntegerField()),
                ('extinção', models.BigIntegerField(blank=True, null=True)),
                ('descrição', models.TextField(blank=True, null=True)),
                ('description_language_II', models.TextField(blank=True, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='imagens/')),
                ('image_2', models.FileField(blank=True, null=True, upload_to='imagens/')),
                ('image_3', models.FileField(blank=True, null=True, upload_to='imagens/')),
                ('antepassados', models.ManyToManyField(blank=True, null=True, to='home.Reino')),
                ('dominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.dominio')),
                ('tags', models.ManyToManyField(to='home.Tag')),
            ],
            options={
                'verbose_name_plural': 'Reinos',
            },
        ),
        migrations.CreateModel(
            name='Ordem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('nome_popular', models.CharField(blank=True, max_length=100, null=True)),
                ('origem', models.BigIntegerField()),
                ('extinção', models.BigIntegerField(blank=True, null=True)),
                ('descrição', models.TextField(blank=True, null=True)),
                ('description_language_II', models.TextField(blank=True, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='imagens/')),
                ('image_2', models.FileField(blank=True, null=True, upload_to='imagens/')),
                ('image_3', models.FileField(blank=True, null=True, upload_to='imagens/')),
                ('antepassados', models.ManyToManyField(blank=True, null=True, to='home.Ordem')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.classe')),
                ('tags', models.ManyToManyField(to='home.Tag')),
            ],
            options={
                'verbose_name_plural': 'Ordens',
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('nome_popular', models.CharField(blank=True, max_length=100, null=True)),
                ('origem', models.BigIntegerField()),
                ('extinção', models.BigIntegerField(blank=True, null=True)),
                ('descrição', models.TextField(blank=True, null=True)),
                ('description_language_II', models.TextField(blank=True, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='imagens/')),
                ('image_2', models.FileField(blank=True, null=True, upload_to='imagens/')),
                ('image_3', models.FileField(blank=True, null=True, upload_to='imagens/')),
                ('antepassados', models.ManyToManyField(blank=True, null=True, to='home.Genero')),
                ('familia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.familia')),
                ('tags', models.ManyToManyField(to='home.Tag')),
            ],
            options={
                'verbose_name_plural': 'Generos',
            },
        ),
        migrations.CreateModel(
            name='Filo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('nome_popular', models.CharField(blank=True, max_length=100, null=True)),
                ('origem', models.BigIntegerField()),
                ('extinção', models.BigIntegerField(blank=True, null=True)),
                ('descrição', models.TextField(blank=True, null=True)),
                ('description_language_II', models.TextField(blank=True, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='imagens/')),
                ('image_2', models.FileField(blank=True, null=True, upload_to='imagens/')),
                ('image_3', models.FileField(blank=True, null=True, upload_to='imagens/')),
                ('antepassados', models.ManyToManyField(blank=True, null=True, to='home.Filo')),
                ('reino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.reino')),
                ('tags', models.ManyToManyField(to='home.Tag')),
            ],
            options={
                'verbose_name_plural': 'Filos',
            },
        ),
        migrations.AddField(
            model_name='familia',
            name='ordem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.ordem'),
        ),
        migrations.AddField(
            model_name='familia',
            name='tags',
            field=models.ManyToManyField(to='home.Tag'),
        ),
        migrations.AddField(
            model_name='especie',
            name='genero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.genero'),
        ),
        migrations.AddField(
            model_name='especie',
            name='tags',
            field=models.ManyToManyField(to='home.Tag'),
        ),
        migrations.AddField(
            model_name='dominio',
            name='tags',
            field=models.ManyToManyField(to='home.Tag'),
        ),
        migrations.AddField(
            model_name='dominio',
            name='vida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.vida'),
        ),
        migrations.AddField(
            model_name='classe',
            name='filo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.filo'),
        ),
        migrations.AddField(
            model_name='classe',
            name='tags',
            field=models.ManyToManyField(to='home.Tag'),
        ),
    ]
