# Generated by Django 4.0.2 on 2022-02-18 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_vida_origem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vida',
            name='origem',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
